function qz_sol = planar_133222_sol_z(in1,in2,in3)
%PLANAR_133222_SOL_Z
%    QZ_SOL = PLANAR_133222_SOL_Z(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Feb-2024 14:39:33

P11_1 = in1(1,:);
P11_2 = in1(2,:);
P11_3 = in1(3,:);
P21_1 = in2(1,:);
P21_2 = in2(2,:);
P21_3 = in2(3,:);
qx = in3(1,:);
qy = in3(2,:);
qz_sol = -(P11_1.*qx-P21_1.*qx+P11_2.*qy-P21_2.*qy)./(P11_3-P21_3);
end
